# Generated by Django 5.1.4 on 2025-01-16 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_available_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mainimage',
            new_name='prodect_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
    ]
