# Generated by Django 5.1.4 on 2025-01-16 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_mainimage_product_prodect_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-created_dt',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='created',
            new_name='created_dt',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_name',
        ),
    ]
